import CodeInput from "components/codeInput";
import ContentSelector from "components/contentSelector.tsx";
import ContentWrapper from "components/generals/ContentWrapper";
import SectionTitle from "components/generals/SectionTitle";
import Header from "components/header";
import RecentShares from "components/recentShares";
import Head from "next/head";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Quick Transfer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ContentWrapper>
        <div className="flex flex-col gap-4">
          <SectionTitle>Insert the transfer code</SectionTitle>
          <CodeInput />
        </div>
        <div className="flex flex-col gap-4">
          <SectionTitle>
            Select the type of content you wanna share
          </SectionTitle>
          <ContentSelector />
        </div>
        <div className="flex flex-col gap-4">
          <SectionTitle>
            Recent shares
          </SectionTitle>
          <RecentShares />
        </div>
      </ContentWrapper>
    </>
  );
}
