import CodeInput from "components/codeInput";
import ContentSelector from "components/contentSelector.tsx";
import ContentWrapper from "components/generals/ContentWrapper";
import SectionTitle from "components/generals/SectionTitle";
import Header from "components/header";
import Head from "next/head";
import { FormEvent, useState } from "react";
import { ShareImage, ShareText } from "utils/customInterfaces";
import getDate from "utils/getDate";
import handleShareImage from "utils/share/handleShareImage";
import handleShareText from "utils/share/handleShareText";

const initialState: ShareImage = {
  image: null,
  timeLimit: "",
  public: true,
};

export default function ShareImagePage() {
  const [shareImage, setShareImage] = useState<ShareImage>(initialState);

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    handleShareImage(shareImage);
  };

  return (
    <>
      <Head>
        <title>Share Image</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ContentWrapper>
        <div className="flex flex-col gap-4">
          <SectionTitle>Select the image</SectionTitle>
          <form
            className="flex items-center flex-col gap-6"
            onSubmit={handleSubmit}
          >
            <label
              htmlFor="image"
              className="
                px-8
                py-2 
                rounded-lg
                border-2
                border-violet-500 
                text-violet-500
                font-semibold 
                cursor-pointer
                hover:scale-110
                transition-transform
            
            "
            >
              {shareImage.image
                ? shareImage.image.name
                : "Select a image"}
              <input
                id="image"
                type="file"
                name="image"
                accept="image/*"
                className="hidden"
                value={""}
                onChange={(e) =>
                  setShareImage({
                    ...shareImage,
                    image: e.target.files![0],
                  })
                }
              />
            </label>
            <input
              type="datetime-local"
              name="timeLimit"
              value={shareImage.timeLimit}
              onChange={(e) =>
                setShareImage({
                  ...shareImage,
                  timeLimit: e.target.value,
                })
              }
            />
            <input
              type="checkbox"
              name="public"
              checked={shareImage.public}
              onChange={(e) =>
                setShareImage({
                  ...shareImage,
                  public: !shareImage.public,
                })
              }
            />
            <input
              className="
            px-8
            py-2 
            rounded-lg
            bg-violet-500 
            text-white 
            font-semibold 
            cursor-pointer
            hover:brightness-90
            transition-all
            "
              type="submit"
              value="Share"
            />
          </form>
        </div>
      </ContentWrapper>
    </>
  );
}
