import CodeInput from "components/codeInput";
import ContentSelector from "components/contentSelector.tsx";
import ContentWrapper from "components/generals/ContentWrapper";
import SectionTitle from "components/generals/SectionTitle";
import Header from "components/header";
import Head from "next/head";
import { FormEvent, useState } from "react";
import { ShareText } from "utils/customInterfaces";
import getDate from "utils/getDate";
import handleShareText from "utils/share/handleShareText";

const initialState: ShareText = {
  content: "",
  timeLimit: "",
  public: true,
};

export default function ShareTextPage() {
  const [shareText, setShareText] = useState<ShareText>(initialState);

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    handleShareText(shareText);
  };

  return (
    <>
      <Head>
        <title>Share Text</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ContentWrapper>
        <div className="flex flex-col gap-4">
          <SectionTitle>Insert text</SectionTitle>
          <form
            className="flex items-center flex-col gap-6"
            onSubmit={handleSubmit}
          >
            <textarea
              value={shareText?.content}
              onChange={(e) =>
                setShareText({ ...shareText, content: e.target.value })
              }
              className="w-full p-4 border text-xl rounded-lg"
              name="text"
              id=""
              cols={30}
              rows={15}
            ></textarea>
            <input
              type="datetime-local"
              name="timeLimit"
              value={shareText.timeLimit}
              onChange={(e) =>
                setShareText({
                  ...shareText,
                  timeLimit: e.target.value,
                })
              }
            />
            <input
              type="checkbox"
              name="public"
              checked={shareText.public}
              onChange={(e) =>
                setShareText({
                  ...shareText,
                  public: !shareText.public,
                })
              }
            />
            <input
              className="
            px-8
            py-2 
            rounded-lg
            bg-violet-500 
            text-white 
            font-semibold 
            cursor-pointer
            hover:brightness-90
            transition-all
            "
              type="submit"
              value="Share"
            />
          </form>
        </div>
      </ContentWrapper>
    </>
  );
}
